version: '3.3'

services:
  njs: #container do NestJS
    build: .
    ports:
      - '3000:3000'
    container_name: 'project-00'
    restart: always #faz com que o compose sempre rode na ultima versao do projeto
